*** Variables ***
${addNewVendor}  //button[text() = "NEW"]
${vendorName}  //input[@id = "partner__name"]
${typeOfPartner}  //span[text() = "Type"]/../../../div[2]/div/span[2]
${vendorEmail}  //input[@name = "email"]
${vendorAddress}  //input[@name = "address"]
${vendorCountry}  //span[text() = "Country"]/../../../div[2]/div/span[2]
${vendorState}  //span[text() = "State"]/../../../div[2]/div/span[2]
${vendorCity}  //span[text() = "City"]/../../../div[2]/div/span[2]
${vendorGSTN}  //input[@id='partner__gstin']
${savePartner}  //button[text() = "Save Partner"]
${vendorback}  (//*[name()='svg'][@id='back_btn'])[1]
${deactivate_vendor}  //button[@id = "vendors__deactivate_btn"]
${Submit}  //button[text() = "Submit"]
${newRequest}  //div[text() = "Create New"]/..
${customerCountryXpath}  //div[@name='country']
${customerStateXpath}   //div[@name='state']
${customerCityXpath}  //div[@name='city']
${csvuploadbutton}   (//*[name()='svg'][@id='vendors_upload_csv'])[1]
${sampleCSV}  //button[normalize-space()='Sample CSV']
${uploadcsvbuttonsecond}  (//button[normalize-space()='upload file'])[1]
${submitcsvbutton}  //button[normalize-space()='Submit File']